version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: unless-stopped
    env_file:
      - .env                  # contains at least MY_API_KEY=… and (optionally) DATABASE_URL=…
    ports:
      - "5711:5711"           # publish so your host‐nginx can reach it
    volumes:
      - ./data:/app/data      # persist your SQLite file (see note below)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5711/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

# (Optional) define a named volume instead of a host bind:
# volumes:
#   data:
#     driver: local

